### ISSUE TITLE
App crashes when "share" is clicked.

### ISSUE THREAD

**Issue by dipu989** [fossasia/open-event-organizer-android#1951]
**Describe the bug**
After creating new event, app crashes when "share" option is clicked.

**To Reproduce**

1. Create a new Event.
2. Open Navigation Drawer.
3. Click on share option.

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | realme x |
|Android Version| Pie 9   |

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other: Open to all.

**Comment by dipu989** [comment]
@iamareebjamal @liveHarshit @ShridharGoel  
What is the expected action after Share option is clicked?

**Comment by dipu989** [comment]
@iamareebjamal @liveHarshit @ShridharGoel  
What is the expected action after Share option is clicked?

**Comment by iamareebjamal** [comment]
Not crashing

**Comment by dipu989** [comment]
![20191001_225823-min](https://user-images.githubusercontent.com/31280303/65986296-2e599080-e4a1-11e9-8b3c-cf5e73ad73a7.gif)
This is the case with my device.

**Comment by iamareebjamal** [comment]
Paste the logs please

**Comment by dipu989** [comment]
```
2019-10-03 00:31:24.963 695-695/com.eventyay.organizer E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.eventyay.organizer, PID: 695
    java.lang.RuntimeException: StrictMode ThreadPolicy violation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onThreadPolicyViolation(StrictMode.java:1705)
        at android.os.StrictMode$AndroidBlockGuardPolicy.handleViolationWithTimingAttempt(StrictMode.java:1562)
        at android.os.StrictMode.readAndHandleBinderCallViolations(StrictMode.java:2141)
        at android.os.Parcel.readExceptionCode(Parcel.java:1912)
        at android.os.Parcel.readException(Parcel.java:1881)
        at com.android.internal.app.IHypnusService$Stub$Proxy.hypnusSetSignatureAction(IHypnusService.java:341)
        at com.oppo.hypnus.HypnusManager.hypnusSetSignatureAction(HypnusManager.java:272)
        at android.app.ActivityThread.acquirePerformance(ActivityThread.java:3252)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3270)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2012)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:227)
        at android.app.ActivityThread.main(ActivityThread.java:7200)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:575)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:903)
     Caused by: android.os.strictmode.DiskWriteViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onWriteToDisk(StrictMode.java:1460)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:180)
        at com.oppo.hypnus.Hypnus.hypnusSetAction(Hypnus.java:499)
        at com.android.server.oppo.HypnusService.dohypnusSetAction(HypnusService.java:240)
        at com.android.server.oppo.HypnusService.hypnusSetSignatureAction(HypnusService.java:251)
        at com.android.internal.app.IHypnusService$Stub.onTransact(IHypnusService.java:123)
        at android.os.Binder.execTransact(Binder.java:731)
2019-10-03 00:31:24.979 695-695/? I/Process: Sending signal. PID: 695 SIG: 9
```

@iamareebjamal  After I installed it using the development branch, app is not launched!
Above quoted error is coming.

**Comment by iamareebjamal** [comment]
Try disabling strict mode in Application subclass

**Comment by dipu989** [comment]
@iamareebjamal Sorry for this late! 
Saw strict mode class in android, are you asking to set the boolean value in StrictMode.java file to false?
```    private static final boolean LOG_V = false;
```
Or anything other?

**Comment by iamareebjamal** [comment]
Yes

**Comment by dipu989** [comment]
Still the same problem.
I have set LOG_V variable false in StrictMode.java file
``` private static final boolean LOG_V = false;```

LogCat comes out to be same - 
```
019-10-12 01:37:20.786 1860-1860/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.eventyay.organizer, PID: 1860
    java.lang.RuntimeException: StrictMode ThreadPolicy violation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onThreadPolicyViolation(StrictMode.java:1705)
        at android.os.StrictMode$AndroidBlockGuardPolicy.handleViolationWithTimingAttempt(StrictMode.java:1562)
        at android.os.StrictMode.readAndHandleBinderCallViolations(StrictMode.java:2141)
        at android.os.Parcel.readExceptionCode(Parcel.java:1912)
        at android.os.Parcel.readException(Parcel.java:1881)
        at com.android.internal.app.IHypnusService$Stub$Proxy.hypnusSetSignatureAction(IHypnusService.java:341)
        at com.oppo.hypnus.HypnusManager.hypnusSetSignatureAction(HypnusManager.java:272)
        at android.app.ActivityThread.acquirePerformance(ActivityThread.java:3252)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3270)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2012)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:227)
        at android.app.ActivityThread.main(ActivityThread.java:7200)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:575)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:903)
     Caused by: android.os.strictmode.DiskWriteViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onWriteToDisk(StrictMode.java:1460)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:180)
        at com.oppo.hypnus.Hypnus.hypnusSetAction(Hypnus.java:499)
        at com.android.server.oppo.HypnusService.dohypnusSetAction(HypnusService.java:240)
        at com.android.server.oppo.HypnusService.hypnusSetSignatureAction(HypnusService.java:251)
        at com.android.internal.app.IHypnusService$Stub.onTransact(IHypnusService.java:123)
        at android.os.Binder.execTransact(Binder.java:731)
```

**Comment by iamareebjamal** [comment]
https://github.com/fossasia/open-event-organizer-android/blob/c9b8a8f29a53bacbfbaa79ef71ae86092cf32217/app/src/main/java/com/eventyay/organizer/OrgaApplication.java#L75-L93

**Comment by dipu989** [comment]
@iamareebjamal  Got rid of  Strict mode! Thanks.
Now Share feature is working fine. No idea, why it was crashing before.
![ezgif com-optimize](https://user-images.githubusercontent.com/31280303/66683203-8314bc80-ec94-11e9-8f77-51f4937de039.gif)
