### ISSUE TITLE
App crashes on selecting NAME or TICKET option in CheckIn(Attendees)

### ISSUE THREAD

**Issue by Saransh0905** [fossasia/open-event-organizer-android#1990]
**Describe the bug**
App closes suddenly when selecting option Name or Ticket from the menu items(top right corner) in Attendees window.
**To Reproduce**
1.Create a event.
2. Open the created event.
3. Select to CHECK IN option(Attendees activity will open up)
4. From the top right options Select either Name or Ticket.
Here, the app crashes.

**Expected behavior**

**Logs**

**Screenshots**
![WhatsApp Image 2019-12-06 at 7 37 36 PM](https://user-images.githubusercontent.com/48832748/70328993-562df180-1860-11ea-908f-2faf5cc50143.jpeg)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         ||
|Android Version|    |

**Additional context**

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by Saransh0905** [comment]
@liveHarshit 
I want to work on this issue but I am a beginner.
Can you guide me?
Thank you

**Comment by liveHarshit** [comment]
> @liveHarshit
> I want to work on this issue but I am a beginner.
> Can you guide me?
> Thank you

Provide crashing logs.

**Comment by Saransh0905** [comment]
2019-12-06 21:32:20.292 13132-13187/com.eventyay.organizer E/libc: Access denied finding property "vendor.debug.egl.swapinterval"
    
    --------- beginning of crash
2019-12-06 21:32:20.296 13132-13132/com.eventyay.organizer E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.eventyay.organizer, PID: 13132
    java.lang.ClassCastException: com.mikepenz.fastadapter.utils.DefaultItemListImpl cannot be cast to com.mikepenz.fastadapter.utils.ComparableItemListImpl
        at com.eventyay.organizer.core.attendee.list.AttendeesFragment.sortAttendees(AttendeesFragment.java:159)
        at com.eventyay.organizer.core.attendee.list.AttendeesFragment.onOptionsItemSelected(AttendeesFragment.java:148)
        at androidx.fragment.app.Fragment.performOptionsItemSelected(Fragment.java:2796)
        at androidx.fragment.app.FragmentManager.dispatchOptionsItemSelected(FragmentManager.java:3195)
        at androidx.fragment.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:412)
        at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:389)
        at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:219)
        at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
        at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
        at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:64)
        at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:207)
        at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:781)
        at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
        at androidx.appcompat.view.menu.SubMenuBuilder.dispatchMenuItemSelected(SubMenuBuilder.java:90)
        at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
        at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
        at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
        at android.widget.AdapterView.performItemClick(AdapterView.java:318)
        at android.widget.AbsListView.performItemClick(AbsListView.java:1201)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3178)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-12-06 21:32:20.313 13132-13187/com.eventyay.organizer E/libc: Access denied finding property "vendor.debug.egl.swapinterval"

**Comment by ankit2019j** [comment]
@liveHarshit 
can i work on this?

**Comment by Sid911** [comment]
@liveHarshit can I work on it... no developement seem to have been taking place 😇

**Comment by Prashant830** [comment]
Can I solve this problem
