### ISSUE TITLE
bug: crash when describe event left empty and back pressed

### ISSUE THREAD

**Issue by 991rajat** [fossasia/open-event-organizer-android#2065]
**Describe the bug**
App crashes in Update Event Fragment when describing the event text view is left empty and back 
the button is pressed.

**To Reproduce**
1. Go to any event.
2. Click Update Event.
3. Briefly describe the event editor left empty.
4. Back Button is pressed.

**Expected behavior**
Crash Must Not Happen if no changes or text view is empty.

**Logs**
FATAL EXCEPTION: main
    Process: com.eventyay.organizer, PID: 13204
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
        at com.eventyay.organizer.ui.editor.RichEditorActivity.onBackPressed(RichEditorActivity.java:116)
        at com.eventyay.organizer.ui.editor.RichEditorActivity.onOptionsItemSelected(RichEditorActivity.java:103)
        at android.app.Activity.onMenuItemSelected(Activity.java:3208)
        at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:383)
        at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:219)
        at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
        at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
        at androidx.appcompat.widget.ToolbarWidgetWrapper$1.onClick(ToolbarWidgetWrapper.java:188)
        at android.view.View.performClick(View.java:5637)
        at android.view.View$PerformClick.run(View.java:22433)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6186)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Screenshots**

![GIF-200130_205531](https://user-images.githubusercontent.com/38184186/73463360-22c09c80-43a3-11ea-8910-5e03e03e1a8a.gif)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | Moto E2 |
|Android Version| 7.1.2 Nougat  |

**Would you like to work on the issue?**

- [x] Yes

**Comment by 991rajat** [comment]
Is anyone facing this issue?

**Comment by adiig7** [comment]
Can I work on this?

**Comment by liveHarshit** [comment]
@adiig7 Take one issue at once, raise PR, take another, thanks

**Comment by adiig7** [comment]
> @adiig7 Take one issue at once, raise PR, take another, thanks 

Yup okay, thanks.

**Comment by nileshteji** [comment]
@adiig7  still working on the issue?

**Comment by iamareebjamal** [comment]
@nileshteji No, go ahead
